### ISSUE TITLE
NULL вместо списка элементов

### ISSUE THREAD

**Issue by Dok11** [aak74/bx-data#3]
Беру первый пример из http://demo.gbdev.xyz/usage/ и получаю `NULL` из getList, не важно, указан `iblockCode` или `iblockId`.

```php
class BlogItems extends \Akop\Element\IbElementOrSection {
  protected $iblockCode = 'CONTENT__BLOG';
}

$blogItemsModel = new BlogItems;
$blogItems = $blogItemsModel->getList();

var_dump($blogItems);
```

Что-то делаю не так?

p.s. Активные элементы в инфоблоке есть, инфоблок 2.0, доступ на чтение тоже есть.
Установлено так:
```js
{
  "require": {
    "aak74/bx-data": "dev-master"
  },
```

**Comment by aak74** [comment]
Можно получить xml для импорта?
